### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Thiffanyariane** [CharlesBrun/sistema-bancario#1]
Olá, Charles!

Parabéns pela tarefa! Gostaria de sugerir que você inclua tratamento de erros mais abrangente para lidar com casos de entrada inválida do usuário. Isso tornará o código mais robusto e capaz de lidar corretamente com diferentes situações de entrada.

**Comment by CharlesBrun** [comment]
> Olá, Charles!
> 
> Parabéns pela tarefa! Gostaria de sugerir que você inclua tratamento de erros mais abrangente para lidar com casos de entrada inválida do usuário. Isso tornará o código mais robusto e capaz de lidar corretamente com diferentes situações de entrada.

Excelente sugestão, obrigado.
